name: Shinsoo_Hizli_Basim
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer_Zorla_Yukle
        run: |
          pip3 install --user Cython==0.29.33 buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sistem_Ve_APK
        run: |
          sudo apt-get update || true
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          yes | buildozer android debug

      - name: Shinsoo_APK_Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Uygulama_Burada
          path: bin/*.apk
          
