name: Shinsoo_APK_Basici
on: workflow_dispatch # Sen butona basınca çalışır

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer_Hazirlik_Ve_Basim
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: master

      - name: Shinsoo_APK_Yukle
        uses: actions/upload-artifact@v2
        with:
          name: Shinsoo_Uygulama_Dosyasi
          path: bin/*.apk
          
