name: Shinsoo_APK_Basici
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04  # Daha stabil olan eski sürüme çektik
    steps:
      - uses: actions/checkout@v4

      - name: Paketleri_Zorla_Kur
        run: |
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user Cython==0.29.33 buildozer

      - name: APK_Basimi
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug

      - name: Shinsoo_APK_Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Shinsoo_Uygulama_Dosyasi
          path: bin/*.apk
          
